var annotated_dup =
[
    [ "CodeMonkey", "namespace_code_monkey.html", [
      [ "MonoBehaviours", "namespace_code_monkey_1_1_mono_behaviours.html", [
        [ "CameraFollow", "class_code_monkey_1_1_mono_behaviours_1_1_camera_follow.html", null ],
        [ "CameraFollowSetup", "class_code_monkey_1_1_mono_behaviours_1_1_camera_follow_setup.html", null ],
        [ "ComponentActions", "class_code_monkey_1_1_mono_behaviours_1_1_component_actions.html", null ],
        [ "PositionRendererSorter", "class_code_monkey_1_1_mono_behaviours_1_1_position_renderer_sorter.html", null ]
      ] ],
      [ "Utils", "namespace_code_monkey_1_1_utils.html", [
        [ "Button_Sprite", "class_code_monkey_1_1_utils_1_1_button___sprite.html", null ],
        [ "Button_UI", "class_code_monkey_1_1_utils_1_1_button___u_i.html", "class_code_monkey_1_1_utils_1_1_button___u_i" ],
        [ "FunctionPeriodic", "class_code_monkey_1_1_utils_1_1_function_periodic.html", null ],
        [ "FunctionTimer", "class_code_monkey_1_1_utils_1_1_function_timer.html", "class_code_monkey_1_1_utils_1_1_function_timer" ],
        [ "FunctionUpdater", "class_code_monkey_1_1_utils_1_1_function_updater.html", null ],
        [ "UI_Bar", "class_code_monkey_1_1_utils_1_1_u_i___bar.html", "class_code_monkey_1_1_utils_1_1_u_i___bar" ],
        [ "UI_BarMultiple", "class_code_monkey_1_1_utils_1_1_u_i___bar_multiple.html", "class_code_monkey_1_1_utils_1_1_u_i___bar_multiple" ],
        [ "UI_Sprite", "class_code_monkey_1_1_utils_1_1_u_i___sprite.html", null ],
        [ "UI_TextComplex", "class_code_monkey_1_1_utils_1_1_u_i___text_complex.html", "class_code_monkey_1_1_utils_1_1_u_i___text_complex" ],
        [ "World_Bar", "class_code_monkey_1_1_utils_1_1_world___bar.html", "class_code_monkey_1_1_utils_1_1_world___bar" ],
        [ "World_Mesh", "class_code_monkey_1_1_utils_1_1_world___mesh.html", "class_code_monkey_1_1_utils_1_1_world___mesh" ],
        [ "World_Sprite", "class_code_monkey_1_1_utils_1_1_world___sprite.html", null ]
      ] ],
      [ "Assets", "class_code_monkey_1_1_assets.html", null ]
    ] ],
    [ "Helper", "namespace_helper.html", [
      [ "CollectionMap", "class_helper_1_1_collection_map.html", null ],
      [ "SmartGCHandle", "class_helper_1_1_smart_g_c_handle.html", null ],
      [ "ThreadSafeDictionary", "class_helper_1_1_thread_safe_dictionary.html", null ]
    ] ],
    [ "RaumfinderEMM", "namespace_raumfinder_e_m_m.html", [
      [ "Datenzugriff", "namespace_raumfinder_e_m_m_1_1_datenzugriff.html", [
        [ "Datenzugriff", "class_raumfinder_e_m_m_1_1_datenzugriff_1_1_datenzugriff.html", "class_raumfinder_e_m_m_1_1_datenzugriff_1_1_datenzugriff" ],
        [ "IDatenzugriff", "interface_raumfinder_e_m_m_1_1_datenzugriff_1_1_i_datenzugriff.html", "interface_raumfinder_e_m_m_1_1_datenzugriff_1_1_i_datenzugriff" ],
        [ "RaumModel", "class_raumfinder_e_m_m_1_1_datenzugriff_1_1_raum_model.html", null ],
        [ "RaumVerfuegbarkeitsModel", "class_raumfinder_e_m_m_1_1_datenzugriff_1_1_raum_verfuegbarkeits_model.html", "class_raumfinder_e_m_m_1_1_datenzugriff_1_1_raum_verfuegbarkeits_model" ]
      ] ],
      [ "Geschaeftslogik", "namespace_raumfinder_e_m_m_1_1_geschaeftslogik.html", [
        [ "Geschaeftslogik", "class_raumfinder_e_m_m_1_1_geschaeftslogik_1_1_geschaeftslogik.html", "class_raumfinder_e_m_m_1_1_geschaeftslogik_1_1_geschaeftslogik" ],
        [ "IGeschaeftslogik", "interface_raumfinder_e_m_m_1_1_geschaeftslogik_1_1_i_geschaeftslogik.html", "interface_raumfinder_e_m_m_1_1_geschaeftslogik_1_1_i_geschaeftslogik" ],
        [ "Raum", "class_raumfinder_e_m_m_1_1_geschaeftslogik_1_1_raum.html", "class_raumfinder_e_m_m_1_1_geschaeftslogik_1_1_raum" ]
      ] ]
    ] ],
    [ "Windows", "namespace_windows.html", [
      [ "Data", "namespace_windows_1_1_data.html", [
        [ "PropertyChangedEventArgs", "class_windows_1_1_data_1_1_property_changed_event_args.html", null ]
      ] ],
      [ "Kinect", "namespace_windows_1_1_kinect.html", [
        [ "AudioBeam", "class_windows_1_1_kinect_1_1_audio_beam.html", null ],
        [ "AudioBeamFrame", "class_windows_1_1_kinect_1_1_audio_beam_frame.html", null ],
        [ "AudioBeamFrameArrivedEventArgs", "class_windows_1_1_kinect_1_1_audio_beam_frame_arrived_event_args.html", null ],
        [ "AudioBeamFrameList", "class_windows_1_1_kinect_1_1_audio_beam_frame_list.html", null ],
        [ "AudioBeamFrameReader", "class_windows_1_1_kinect_1_1_audio_beam_frame_reader.html", null ],
        [ "AudioBeamFrameReference", "class_windows_1_1_kinect_1_1_audio_beam_frame_reference.html", null ],
        [ "AudioBeamSubFrame", "class_windows_1_1_kinect_1_1_audio_beam_sub_frame.html", null ],
        [ "AudioBodyCorrelation", "class_windows_1_1_kinect_1_1_audio_body_correlation.html", null ],
        [ "AudioSource", "class_windows_1_1_kinect_1_1_audio_source.html", null ],
        [ "Body", "class_windows_1_1_kinect_1_1_body.html", null ],
        [ "BodyFrame", "class_windows_1_1_kinect_1_1_body_frame.html", null ],
        [ "BodyFrameArrivedEventArgs", "class_windows_1_1_kinect_1_1_body_frame_arrived_event_args.html", null ],
        [ "BodyFrameReader", "class_windows_1_1_kinect_1_1_body_frame_reader.html", null ],
        [ "BodyFrameReference", "class_windows_1_1_kinect_1_1_body_frame_reference.html", null ],
        [ "BodyFrameSource", "class_windows_1_1_kinect_1_1_body_frame_source.html", null ],
        [ "BodyIndexFrame", "class_windows_1_1_kinect_1_1_body_index_frame.html", null ],
        [ "BodyIndexFrameArrivedEventArgs", "class_windows_1_1_kinect_1_1_body_index_frame_arrived_event_args.html", null ],
        [ "BodyIndexFrameReader", "class_windows_1_1_kinect_1_1_body_index_frame_reader.html", null ],
        [ "BodyIndexFrameReference", "class_windows_1_1_kinect_1_1_body_index_frame_reference.html", null ],
        [ "BodyIndexFrameSource", "class_windows_1_1_kinect_1_1_body_index_frame_source.html", null ],
        [ "CameraIntrinsics", "struct_windows_1_1_kinect_1_1_camera_intrinsics.html", null ],
        [ "CameraSpacePoint", "struct_windows_1_1_kinect_1_1_camera_space_point.html", null ],
        [ "ColorCameraSettings", "class_windows_1_1_kinect_1_1_color_camera_settings.html", null ],
        [ "ColorFrame", "class_windows_1_1_kinect_1_1_color_frame.html", null ],
        [ "ColorFrameArrivedEventArgs", "class_windows_1_1_kinect_1_1_color_frame_arrived_event_args.html", null ],
        [ "ColorFrameReader", "class_windows_1_1_kinect_1_1_color_frame_reader.html", null ],
        [ "ColorFrameReference", "class_windows_1_1_kinect_1_1_color_frame_reference.html", null ],
        [ "ColorFrameSource", "class_windows_1_1_kinect_1_1_color_frame_source.html", null ],
        [ "ColorSpacePoint", "struct_windows_1_1_kinect_1_1_color_space_point.html", null ],
        [ "CoordinateMapper", "class_windows_1_1_kinect_1_1_coordinate_mapper.html", null ],
        [ "CoordinateMappingChangedEventArgs", "class_windows_1_1_kinect_1_1_coordinate_mapping_changed_event_args.html", null ],
        [ "DepthFrame", "class_windows_1_1_kinect_1_1_depth_frame.html", null ],
        [ "DepthFrameArrivedEventArgs", "class_windows_1_1_kinect_1_1_depth_frame_arrived_event_args.html", null ],
        [ "DepthFrameReader", "class_windows_1_1_kinect_1_1_depth_frame_reader.html", null ],
        [ "DepthFrameReference", "class_windows_1_1_kinect_1_1_depth_frame_reference.html", null ],
        [ "DepthFrameSource", "class_windows_1_1_kinect_1_1_depth_frame_source.html", null ],
        [ "DepthSpacePoint", "struct_windows_1_1_kinect_1_1_depth_space_point.html", null ],
        [ "FrameCapturedEventArgs", "class_windows_1_1_kinect_1_1_frame_captured_event_args.html", null ],
        [ "FrameDescription", "class_windows_1_1_kinect_1_1_frame_description.html", null ],
        [ "InfraredFrame", "class_windows_1_1_kinect_1_1_infrared_frame.html", null ],
        [ "InfraredFrameArrivedEventArgs", "class_windows_1_1_kinect_1_1_infrared_frame_arrived_event_args.html", null ],
        [ "InfraredFrameReader", "class_windows_1_1_kinect_1_1_infrared_frame_reader.html", null ],
        [ "InfraredFrameReference", "class_windows_1_1_kinect_1_1_infrared_frame_reference.html", null ],
        [ "InfraredFrameSource", "class_windows_1_1_kinect_1_1_infrared_frame_source.html", null ],
        [ "IsAvailableChangedEventArgs", "class_windows_1_1_kinect_1_1_is_available_changed_event_args.html", null ],
        [ "Joint", "struct_windows_1_1_kinect_1_1_joint.html", null ],
        [ "JointOrientation", "struct_windows_1_1_kinect_1_1_joint_orientation.html", null ],
        [ "KinectBuffer", "class_windows_1_1_kinect_1_1_kinect_buffer.html", null ],
        [ "KinectSensor", "class_windows_1_1_kinect_1_1_kinect_sensor.html", null ],
        [ "KinectUnityAddinUtils", "class_windows_1_1_kinect_1_1_kinect_unity_addin_utils.html", null ],
        [ "LongExposureInfraredFrame", "class_windows_1_1_kinect_1_1_long_exposure_infrared_frame.html", null ],
        [ "LongExposureInfraredFrameArrivedEventArgs", "class_windows_1_1_kinect_1_1_long_exposure_infrared_frame_arrived_event_args.html", null ],
        [ "LongExposureInfraredFrameReader", "class_windows_1_1_kinect_1_1_long_exposure_infrared_frame_reader.html", null ],
        [ "LongExposureInfraredFrameReference", "class_windows_1_1_kinect_1_1_long_exposure_infrared_frame_reference.html", null ],
        [ "LongExposureInfraredFrameSource", "class_windows_1_1_kinect_1_1_long_exposure_infrared_frame_source.html", null ],
        [ "MultiSourceFrame", "class_windows_1_1_kinect_1_1_multi_source_frame.html", null ],
        [ "MultiSourceFrameArrivedEventArgs", "class_windows_1_1_kinect_1_1_multi_source_frame_arrived_event_args.html", null ],
        [ "MultiSourceFrameReader", "class_windows_1_1_kinect_1_1_multi_source_frame_reader.html", null ],
        [ "MultiSourceFrameReference", "class_windows_1_1_kinect_1_1_multi_source_frame_reference.html", null ],
        [ "PointF", "struct_windows_1_1_kinect_1_1_point_f.html", null ],
        [ "Vector4", "struct_windows_1_1_kinect_1_1_vector4.html", null ]
      ] ]
    ] ],
    [ "AbstractKinectUICursor", "class_abstract_kinect_u_i_cursor.html", "class_abstract_kinect_u_i_cursor" ],
    [ "Bedienungshilfe", "class_bedienungshilfe.html", "class_bedienungshilfe" ],
    [ "BodySourceManager", "class_body_source_manager.html", null ],
    [ "BodySourceView", "class_body_source_view.html", null ],
    [ "BookingSummaryButtonController", "class_booking_summary_button_controller.html", "class_booking_summary_button_controller" ],
    [ "Buchungsübersicht", "class_buchungsu_xCC_x88bersicht.html", "class_buchungsu_xCC_x88bersicht" ],
    [ "Buchungsuebersicht", "class_buchungsuebersicht.html", "class_buchungsuebersicht" ],
    [ "CaptureScreenShot", "class_capture_screen_shot.html", null ],
    [ "Click", "class_click.html", null ],
    [ "ColorSourceManager", "class_color_source_manager.html", null ],
    [ "ColorSourceView", "class_color_source_view.html", null ],
    [ "DepthSourceManager", "class_depth_source_manager.html", null ],
    [ "DepthSourceView", "class_depth_source_view.html", null ],
    [ "DisableOnStart", "class_disable_on_start.html", null ],
    [ "DropDownNavigationKinect", "class_drop_down_navigation_kinect.html", "class_drop_down_navigation_kinect" ],
    [ "DropdownUtils", "class_dropdown_utils.html", null ],
    [ "Englisch", "class_englisch.html", null ],
    [ "FilteredSearchButtonController", "class_filtered_search_button_controller.html", "class_filtered_search_button_controller" ],
    [ "InfraredSourceManager", "class_infrared_source_manager.html", null ],
    [ "InfraredSourceView", "class_infrared_source_view.html", null ],
    [ "KinectInputData", "class_kinect_input_data.html", "class_kinect_input_data" ],
    [ "KinectInputModule", "class_kinect_input_module.html", "class_kinect_input_module" ],
    [ "KinectUICursor", "class_kinect_u_i_cursor.html", "class_kinect_u_i_cursor" ],
    [ "KinectUIWaitCursor", "class_kinect_u_i_wait_cursor.html", "class_kinect_u_i_wait_cursor" ],
    [ "KinectUIWaitOverButton", "class_kinect_u_i_wait_over_button.html", null ],
    [ "Kriteriensuche", "class_kriteriensuche.html", "class_kriteriensuche" ],
    [ "Logik", "class_logik.html", "class_logik" ],
    [ "MainMenuButtonController", "class_main_menu_button_controller.html", "class_main_menu_button_controller" ],
    [ "MultiSourceManager", "class_multi_source_manager.html", null ],
    [ "SearchResultButtonController", "class_search_result_button_controller.html", "class_search_result_button_controller" ],
    [ "SpeechToCommand", "class_speech_to_command.html", "class_speech_to_command" ],
    [ "Sprachauswahl", "class_sprachauswahl.html", "class_sprachauswahl" ],
    [ "Startmenu", "class_startmenu.html", "class_startmenu" ],
    [ "StartMenuButtonControllers", "class_start_menu_button_controllers.html", "class_start_menu_button_controllers" ],
    [ "SuchergebnisKS", "class_suchergebnis_k_s.html", "class_suchergebnis_k_s" ]
];